### ISSUE TITLE
When dark mode is turned on, the text on the admin page is barely readable

### ISSUE THREAD

**Issue by SKevo18** [FriendsOfFlarum/pages#21]
![image](https://user-images.githubusercontent.com/39010496/92319846-c8fd1080-f01c-11ea-937a-992f7f327c6c.png)

"Home" is hardly readable. The text should be black. Only occurs in dark mode (the text is black while the forum is at white mode).

Primary color: `#ff9d00`
Secondary color: `#00b7ff`

https://github.com/FriendsOfFlarum/pages/blob/1d579f0a5caeb81065fc73d0cc749d76bb60e0c9/resources/less/admin.less#L43-L47

Adding `color: black;` below the `border-top` property should fix the problem.

**Comment by clarkwinkelmann** [comment]
I'd say the issue is actually at line 49. We should have a darker odd-even pattern in dark mode and not use that light grey background in dark mode. On that line we need to use a Flarum color variable that's theme-dependend, or add a switch with a different color for dark mode.

But I don't think Flarum has any alternating pattern built-in, so we might be better defining our own darkmode background color for that pattern.

https://github.com/FriendsOfFlarum/pages/blob/1d579f0a5caeb81065fc73d0cc749d76bb60e0c9/resources/less/admin.less#L49

**Comment by SKevo18** [comment]
That might work, I can confirm that when I made 1 more page, the color of the background was black, text was white so it fit.
