### ISSUE TITLE
Should the title be set as H1?

### ISSUE THREAD

**Issue by efast1568** [FriendsOfFlarum/pages#51]
m("h2", { className: "PageHero-title" })

Should the title be set as H1?

**Comment by clarkwinkelmann** [comment]
Yes, we should change it.

The reason `h2` was used is most likely historical: up to Flarum 1.6, Flarum (somewhat incorrectly) used `h1` for the site name, so it was not semantically correct to inject another `h1` tag.

Since Flarum 1.7 this "problem" has been fixed and Flarum has updated its own `h2` titles to `h1`. So we should do the same in this extension now.
